---
title: 'SSN2: The next generation of spatial stream network modeling in R'
tags:
  - R
  - Spatial stream network
  - Spatial correlation
  - Spatial prediction
  - Linear model
  - Generalized linear model
  - Torgegram
authors:
  - name: Michael Dumelle
    orcid: 0000-0002-3393-5529
    affiliation: "1" # (Multiple affiliations must be quoted)
  - name: Erin Peterson
    affiliation: 2
  - name: Jay M. Ver Hoef
    affiliation: 3
  - name: Alan Pearse
    affiliation: 4
  - name: Dan Isaak
    affiliation: 2
affiliations:
 - name: United States Environmental Protection Agency
   index: 1
 - name: Queensland University of Technology
   index: 2
 - name: United States National Oceanic and Atmospheric Administration
   index: 3
 - name: University of Wollongong
   index: 4
 - name: United States Forest Service
   index: 5
citation_author: Dumelle et. al.
date: 11 November 2023
year: 2023
bibliography: paper.bib
output: rticles::joss_article
csl: apa.csl
journal: JOSS
---

# Summary

This is a summary. This is a citation @ver2014ssn.

# Statement of Need

This is a statement of need.

# Package Overview

# Discussion

# Acknowledgements

The views expressed in this manuscript are those of the authors and do not necessarily represent the views or policies of the U.S. Environmental Protection Agency or the National Oceanic and Atmospheric Administration. Any mention of trade names, products, or services does not imply an endorsement by the U.S. government, the U.S. Environmental Protection Agency, or the National Oceanic and Atmospheric Administration. The U.S. Environmental Protection Agency and the National Oceanic and Atmospheric Administration do not endorse any commercial products, services or enterprises.

# References
